/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package modelo.vista;

/**
 *
 * @author ALEX
 */
public class PnlFoot extends javax.swing.JPanel {

    /**
     * Creates new form pnlHomeCenterFoot
     */
    public PnlFoot() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgNuevo = new javax.swing.JPanel();
        lblNuevo = new javax.swing.JLabel();
        bgEditar = new javax.swing.JPanel();
        lblEditar = new javax.swing.JLabel();
        bgEliminar = new javax.swing.JPanel();
        lblEliminar = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5));

        bgNuevo.setBackground(new java.awt.Color(0, 204, 102));

        lblNuevo.setBackground(new java.awt.Color(0, 0, 0));
        lblNuevo.setForeground(new java.awt.Color(255, 255, 255));
        lblNuevo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNuevo.setText("NUEVO");

        javax.swing.GroupLayout bgNuevoLayout = new javax.swing.GroupLayout(bgNuevo);
        bgNuevo.setLayout(bgNuevoLayout);
        bgNuevoLayout.setHorizontalGroup(
            bgNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        bgNuevoLayout.setVerticalGroup(
            bgNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        add(bgNuevo);

        bgEditar.setBackground(new java.awt.Color(0, 51, 255));

        lblEditar.setBackground(new java.awt.Color(0, 0, 0));
        lblEditar.setForeground(new java.awt.Color(255, 255, 255));
        lblEditar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEditar.setText("EDITAR");

        javax.swing.GroupLayout bgEditarLayout = new javax.swing.GroupLayout(bgEditar);
        bgEditar.setLayout(bgEditarLayout);
        bgEditarLayout.setHorizontalGroup(
            bgEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEditar, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        bgEditarLayout.setVerticalGroup(
            bgEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEditar, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        add(bgEditar);

        bgEliminar.setBackground(new java.awt.Color(255, 51, 102));

        lblEliminar.setBackground(new java.awt.Color(255, 51, 102));
        lblEliminar.setForeground(new java.awt.Color(255, 255, 255));
        lblEliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEliminar.setText("ELIMINAR");

        javax.swing.GroupLayout bgEliminarLayout = new javax.swing.GroupLayout(bgEliminar);
        bgEliminar.setLayout(bgEliminarLayout);
        bgEliminarLayout.setHorizontalGroup(
            bgEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        bgEliminarLayout.setVerticalGroup(
            bgEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        add(bgEliminar);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgEditar;
    private javax.swing.JPanel bgEliminar;
    private javax.swing.JPanel bgNuevo;
    private javax.swing.JLabel lblEditar;
    private javax.swing.JLabel lblEliminar;
    private javax.swing.JLabel lblNuevo;
    // End of variables declaration//GEN-END:variables
}
